### ISSUE TITLE
Forecast does not match the data on the official buienradar app

### ISSUE THREAD

**Issue by CiprianoFreitas** [mjj4791/python-buienradar#11]
I've been using this library to create a [simpler version](https://buienradar.netlify.app/) of the buienradar app to use on my phone.
I noticed that the forecast for the next few days does not match the info displayed on the official app. At first I thought it would be due to a small difference in the lat and long values sent. But the discrepancy is huge.

Am I missing some conversion or is their app using another source?

**Comment by CiprianoFreitas** [comment]
Values I get
![image](https://user-images.githubusercontent.com/2479089/104128615-fe1dc480-5368-11eb-844c-9a6f16fbb0f4.png)

Values from the app
![image](https://user-images.githubusercontent.com/2479089/104128635-1ab9fc80-5369-11eb-8b64-2f9f8c05db5b.png)

**Comment by mjj4791** [comment]
The forecastdata is for the whole country, so your exact location does not matter for the forecast data returned.

Have a look at the returned forecast data; it returns 3 different temperatures per forecast:
- temperature: 
   this is the average max temperature forecasted (ie the average max (day) temperature)
- mintemp: 
   the lowest minimum temperature forecasted (ie mintempmin in the forecasted data)
- maxtemp: 
   this is the highest forecased maximum temperature (ie the maxtempmax in the forecasted data)

Does this explain what you are seeing?
if not, can you supply some examples with the json buienradar data from that time?
https://data.buienradar.nl/2.0/feed/json
