### ISSUE TITLE
Tag the source

### ISSUE THREAD

**Issue by fabaff** [mjj4791/python-buienradar#14]
Could you please tag the source? This allows distributions to get the complete source from GitHub.

It was done 1.0.4 but not for 1.0.5.

Thanks

**Comment by mjj4791** [comment]
done
https://github.com/mjj4791/python-buienradar/tree/1.0.5

**Comment by mweinelt** [comment]
And 1.0.6, pelase.

**Comment by mjj4791** [comment]
done
