### ISSUE TITLE
Add configuration variables to Buienradar sensor

### ISSUE THREAD

**Issue by sean-pk-mcgrath** [mjj4791/python-buienradar#4]
Hi mjj,
I have never created an issue in GitHub before -- apologies if this is the wrong approach. 

I am requesting that rainFallLast24Hour and rainFallLastHour are added as configuration
variables into the buienradar sensor component.

The variables exist in the json file from buienradar.nl, so hopefully they are easy to add (see https://api.buienradar.nl/data/public/2.0/jsonfeed?lat=<51.7>&lon=<5.7> ).

I would have tried to add in your file, but it seems there is now a difference between the xml and json feeds from buienradar (the site says "Let op! Vanaf 12 juni 2018 is de JSON van Buienradar vernieuwd, hierdoor kunnen zelf gebouwde onderdelen op basis van de oude JSON stuk gaan."). It seems json has been updated, but not xml...

cheers,
Sean

**Comment by mjj4791** [comment]
Sean

Thanks for your question; It made me aware that buienradar has published a new version of their API based on Json, where the older is using xml. I will have a look and try to include support for it (it seems there are more parameters in the json api than there were in the xml based api.... so we could add them into homeassistant as well!)

**Comment by mjj4791** [comment]
sean-pk-mcgrath

I have just pushed a new PR to home-assistant to update the buienradar library to version 1.0.1; this library used the new json api by default AND adds new data elements, such as rainlast24hour and rainlasthour.

https://github.com/home-assistant/home-assistant/pull/24463

**Comment by sean-pk-mcgrath** [comment]
Great, thanks for letting me know. I will check it out.
