### ISSUE TITLE
API endpoint changed

### ISSUE THREAD

**Issue by tarmack** [mjj4791/python-buienradar#5]
It seems that the api endpoint of the weather data has changed. It is now only served at "https://data.buienradar.nl/1.0/feed/xml". I didn't test any other weather item than the temperature, so I can not be sure the XML didn't change. Just wanted to alert you and help out anybody else that encounters their weather data stuck.

**Comment by mjj4791** [comment]
tamack

thanks for the heads-up! Took me a while to see this, message....
however, I have pushed a new version of the library (1.0.1) who will  now use the json API by default; support for the xml api is still there as well, should you want to use that.

The library also add some new data elements, which are new in the json api
