### ISSUE TITLE
New json elements failing validation

### ISSUE THREAD

**Issue by sean-pk-mcgrath** [mjj4791/python-buienradar#8]
Hi mjj,

I finally got around to converting to your new json file (thanks for that). However, when I add the "new" json conditions to my configuration yaml, I get a validation error in HA:

> Configuration invalid
Invalid config for [sensor.buienradar]: value is not allowed @ data['monitored_conditions'][6]. Got 'feeltemperature'. (See ?, line ?). Please check the docs at https://home-assistant.io/components/sensor.buienradar/

This happens for all the conditions where you have the comment "# new in json api (>1.0.0):" All the others work fine.

Cheers,
Sean

**Comment by mjj4791** [comment]
hey sean

Do you still have this issue?
I am running the new json api for some time, including the feeltemperature and i am not seeing this.

* Are you still experiencing this?
from the error above it seems you were still running the old buienradar component that did (not yet) support the feeltemperature condition
* Are you running the latest version of HA, which includes the new component and uses the new json api?
* which weather station are you using and does that weather station supply a feeltemperature?

**Comment by sean-pk-mcgrath** [comment]
hi mjj,

Yes, I still have the issue. I am not on the latest version of HA. I use Volkel (6375), which does have the feeltemperature. I had thought that I was on the latest when I reported the bug, but I will update and let you know.

**Comment by sean-pk-mcgrath** [comment]
hi mjj,

I updated HA to v 0.100 and indeed the new variables work now. I guess I hadn't updated after your fix. Apologies for the false alarm.

Sean
