### ISSUE TITLE
Suppress logging of JSON call

### ISSUE THREAD

**Issue by jasperslits** [mjj4791/python-buienradar#9]
As per README.rst: "This package is created as a library for the Home assistant buienradar component implementation". 
So the location is supposed to be static. 

I noticed that this package is logging to the Homeassistant console (docker in my case) upon every invocation, so that's every 10 minutes in a default setup:

2020-02-06 22:06:16 INFO (MainThread) [buienradar.buienradar_json] Parse ws data: latitude: 51.yyyyyy21240234375, longitude: 5.xxx851245532509

So it's coming from buienradar/buienradar_json.py in method __parse_ws_data . 

The issue is that this logger.info() call just creates noise in the HA logs for no good reason and should be changed to loglevel.debug() so it's consistent with the use within the home assistant component which uses debug level for all notifications. 
(Raising an issue is easier for me than creating a PR for now)

**Comment by mjj4791** [comment]
this issue should be fixed with #10  and #13
